version: "3.3"
services:
  db:
    image: mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: awesomepassword123
    ports:
      - "3306:3306"
    networks:
      static-network:
        ipv4_address: 172.20.0.3
  web:
    build: ./
    depends_on: [db]
    links: [db]
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASS: awesomepassword123
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      BUNDLE_PATH: /bundle
    networks:
      static-network:
        ipv4_address: 172.20.0.2
    ports:
      - "3000:3000"
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
